### PR TITLE
Add accent

### PR DESCRIPTION
**Pull request by nopara73**
Either all of us have accent or none of us.

### CODE REVIEW

**Comment by nothingmuch** [comment]
can i have a heavy metal umlaut in that case? i need to decide where to put it

**Comment by MaxHillebrand** [comment]
is it `Adam` now again? it should be have the accent...

**Comment by nothingmuch** [comment]
oof, good catch! this conflicted with the s/draft/Draft/ change and i only noticed the accent on the o when i resolved the conflict.

**Comment by nothingmuch** [comment]
@nopara73 since the bad fix is already, and it's really not any reviewer's business to decide how you want to spell your name, do you mind if you or i just fix directly in master?

**Comment by nopara73** [comment]
Sure. Add your umlaut, too.

**Pull request merged**
